name: Test Minimal Reusable Call
on:
  workflow_dispatch: {}
jobs:
  build-match:
    permissions:
      contents: write
    uses: ./.github/workflows/debug-run.yml
    with:
      match: ""
      depth: "standard"
      model: ""
    secrets: inherit
